### ISSUE TITLE
Unable to install module - node-gyp/node-sass build errors

### ISSUE THREAD

**Issue by mycompassspins** [twilson63/express-couchUser#44]
I'm on node 5.2.0 and npm 3.5.2 on OSX El Capitan. I've got the latest XCode and Command Line Tools. Python 2.7.11. I've tried using node-sass 3.4.2 and their latest beta release. I've updated node-gyp globally. I've removed the node_modules folder, cleaned the cache and ran `npm install`. I can install node-email-templates and node-sass without issue. I get the following errors when trying to install express-user-couchdb:

    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-   gyp/lib/build.js:276:23)
    gyp ERR! stack     at emitTwo (events.js:88:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:173:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)
    gyp ERR! System Darwin 15.3.0
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-   gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/Justin/Code/nec/kRaceSandbox/src/node_modules/express-user-couchdb/node_modules/node-sass
    gyp ERR! node -v v5.2.0
    gyp ERR! node-gyp -v v3.2.1
    gyp ERR! not ok 
    Build failed

and 

    npm ERR! Darwin 15.3.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "express-user-couchdb"
    npm ERR! node v5.2.0
    npm ERR! npm  v3.5.2
    npm ERR! code ELIFECYCLE

    npm ERR! node-sass@0.8.6 install: `node build.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the node-sass@0.8.6 install script 'node build.js'.

I realize there could be a problem anywhere in the chain, so I'm just starting with the module I'm unable to install. Any help would be awesome. Let me know if you need additional info. Thanks!

**Comment by twilson63** [comment]
Ok, I updated the email template module to 2.1 and it appears to fix the issue, all the test pass.

**Comment by mycompassspins** [comment]
Awesome, thanks!
